language: python

python:
    - "2.7"
    - "3.2" # for ubuntu12.04

before_install:
    - sudo apt-get install libboost-python-dev libgraphicsmagick++1-dev

install:
    - pip install --upgrade .

script:
    - make test
