sudo: required
dist: trusty

language: python

matrix:
    include:
        - os: osx
          python: "2.7"
          env: TARGET=macosx
        - os: osx
          python: "3.6"
          env: TARGET=macosx
        - python: "2.7"
          env: TARGET=linux
        - python: "3.4"
          env: TARGET=linux
    allow_failures:
        - python: "3.2"

addons:
    apt:
        packages:
            - libboost-python-dev
            - libgraphicsmagick++1-dev
            - python3-setuptools

before_install:
    - if [[ "$TARGET" == "macosx" ]]; then
          brew update;
          brew upgrade boost-python graphicsmagick
      fi

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2."* ]]; then sudo /usr/bin/python setup.py install; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3."* ]]; then sudo mkdir -p /usr/lib/python3.4/site-packages/ ; sudo /usr/bin/python3 setup.py install; fi

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2."* ]]; then PYTHON=/usr/bin/python make test; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3."* ]]; then PYTHON=/usr/bin/python3 make test; fi
    - ls setup.py
