sudo: required
dist: trusty

language: python

python:
    - "2.7"
    - "3.2" # for ubuntu12.04

before_install:
    - sudo apt-get update && sudo apt-get -y install python-dev libboost-python-dev libgraphicsmagick++1-dev

install:
    - pip install --upgrade .

script:
    - make test
