language: python

python:
    - "2.7"
    - "3.5"

before_install:
    - sudo apt-get install libboost-python-dev libgraphicsmagick++1-dev

install:
    - python setup.py install

script:
    - make test
