dist: trusty

matrix:
    include:
        - os: osx
          env: TARGET=macosx2
        - os: osx
          env: TARGET=macosx3
        - python: "2.7"
          language: python
          env: TARGET=linux
        - python: "3.5"
          language: python
          env: TARGET=linux
          dist: xenial      # use python3.5
    allow_failures:
        - python: "3.2"

addons:
    apt:
        packages:
            - libboost-python-dev
            - libgraphicsmagick++1-dev
            - python3-setuptools
            - gsfonts

before_install:
    - if [[ "$TARGET" == "macosx2" ]]; then
          brew update;
          brew install boost-python graphicsmagick;
          brew outdated boost-python || brew upgrade boost-python;
          brew outdated graphicsmagick || brew upgrade graphicsmagick;
          brew outdated python@2 || brew upgrade python@2;
      fi
    - if [[ "$TARGET" == "macosx3" ]]; then
          brew install python@3.8 boost-python3 graphicsmagick;
          brew outdated boost-python3 || brew upgrade boost-python3;
          brew outdated graphicsmagick || brew upgrade graphicsmagick;
          brew outdated python@3.8 || brew upgrade python@3.8;
      fi

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2."* ]]; then sudo /usr/bin/python setup.py install; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4"* ]]; then sudo mkdir -p /usr/lib/python3.4/site-packages/ ; sudo /usr/bin/python3 setup.py install; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5"* ]]; then sudo mkdir -p /usr/lib/python3.5/site-packages/ ; sudo /usr/bin/python3 setup.py install; fi
    - if [[ "$TARGET" == "macosx2" ]]; then python setup.py install; fi
    - if [[ "$TARGET" == "macosx3" ]]; then /usr/local/opt/python@3.8/bin/python3 setup.py install; fi

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2."* ]]; then PYTHON=/usr/bin/python make test; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3."* ]]; then PYTHON=/usr/bin/python3 make test; fi
    - if [[ "$TARGET" == "macosx2" ]]; then PYTHON=`which python` make test; fi
    - if [[ "$TARGET" == "macosx3" ]]; then PYTHON=/usr/local/opt/python@3.8/bin/python3 make test; fi
    - ls setup.py
