name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 15 * * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']
        exclude:
          - os: macos-latest
            python-version: '3.7'
          - os: macos-latest
            python-version: '3.8'
          - os: macos-latest
            python-version: '3.9'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements on Linux
      run: sudo apt-get install libboost-python-dev libgraphicsmagick++1-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install requirements on macOSX
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install graphicsmagick boost-python3
      if: matrix.os == 'macOS-latest'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Test
      run: |
        make test
